//===============================================================================
// Microsoft patterns & practices
//  Data Access Guide
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// This code released under the terms of the 
// Microsoft patterns & practices license (http://dataguidance.codeplex.com/license)
//===============================================================================


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Repo.Impl.Sql.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.Repo.Impl.Sql.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking credit card registration..
        /// </summary>
        internal static string ErrorCheckingCreditCardRegistration {
            get {
                return ResourceManager.GetString("ErrorCheckingCreditCardRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking order submission with trackingId={0}..
        /// </summary>
        internal static string ErrorCheckingOrderSubmission {
            get {
                return ResourceManager.GetString("ErrorCheckingOrderSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving all StateProvinces..
        /// </summary>
        internal static string ErrorRetrievingAllStateProvinces {
            get {
                return ResourceManager.GetString("ErrorRetrievingAllStateProvinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving inventory for productId={0}..
        /// </summary>
        internal static string ErrorRetrievingInventoryForProductId {
            get {
                return ResourceManager.GetString("ErrorRetrievingInventoryForProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving person by emailAddress={0}..
        /// </summary>
        internal static string ErrorRetrievingPersonByEmailAddress {
            get {
                return ResourceManager.GetString("ErrorRetrievingPersonByEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving person for personIdentifier={0}..
        /// </summary>
        internal static string ErrorRetrievingPersonByIdentifier {
            get {
                return ResourceManager.GetString("ErrorRetrievingPersonByIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving StateProvince by stateProvinceId={0}..
        /// </summary>
        internal static string ErrorRetrievingStateProvinceById {
            get {
                return ResourceManager.GetString("ErrorRetrievingStateProvinceById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving order with trackingId={0}..
        /// </summary>
        internal static string ErrorSavingOrderWithTrackingId {
            get {
                return ResourceManager.GetString("ErrorSavingOrderWithTrackingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving person..
        /// </summary>
        internal static string ErrorSavingPerson {
            get {
                return ResourceManager.GetString("ErrorSavingPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating order with trackingId={0} to orderStatus={1}..
        /// </summary>
        internal static string ErrorUpdatingOrderStatus {
            get {
                return ResourceManager.GetString("ErrorUpdatingOrderStatus", resourceCulture);
            }
        }
    }
}
